# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the jar file into the container
COPY target/spring-monitoring-communication-0.0.1-SNAPSHOT.jar /app/app.jar

# Expose the application's port
EXPOSE 8083

# Run the jar file
ENTRYPOINT ["java", "-jar", "/app/app.jar", "--server.port=8083"]
